ARG DEBIAN_VERSION
ARG PGVERSION
FROM docker.io/library/debian:${DEBIAN_VERSION}-slim AS awscli-installer

# Based on Official Image

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y curl unzip

RUN cd /tmp && \
	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
	-o "awscliv2.zip" && \
	unzip awscliv2.zip && \
	./aws/install --bin-dir /aws-cli-bin/ --update

FROM docker.io/library/debian:${DEBIAN_VERSION}-slim AS base

ENV BACKUP_SCHEDULE=""
ENV BACKUP_RETENTION_DAYS=""
ENV BACKUP_PASSWORD=""
ENV BACKUP_CMD="false"
ENV S3_PREFIX=""
ENV S3_BUCKET=""
ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV TERM=xterm-color

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y \
	cron \
	curl \
	jq \
	vim \
	gnupg2 \
	mandoc && \
	rm -rf /etc/cron.*/*

COPY --chmod=0775 \
	--from=awscli-installer \
	/usr/local/aws-cli/ /usr/local/aws-cli/
COPY --chmod=0775 \
	--from=awscli-installer \
	/aws-cli-bin/ /usr/local/bin/

RUN mkdir -p /opt/parmincloud/backups

COPY --chmod=0775 entrypoint.sh /opt/parmincloud/backups/entrypoint
COPY --chmod=0775 start.sh /opt/parmincloud/backups/start-container
COPY --chmod=0775 utils.sh /opt/parmincloud/backups/utils
COPY --chmod=0775 backup.sh /opt/parmincloud/backups/backup

ENTRYPOINT [ "/opt/parmincloud/backups/entrypoint" ]
CMD ["/opt/parmincloud/backups/start-container"]

FROM base AS file-backup

ENV BACKUP_CMD "/opt/parmincloud/backups/file-backup"
ENV DATA_DIR "/data"

COPY --chmod=0775 file-backup.sh /opt/parmincloud/backups/file-backup

FROM base AS base-pg

ARG DEBIAN_VERSION
ARG PGVERSION

ENV PGHOST=""
ENV PGPORT=""
ENV PGUSER=""
ENV PGPASSWORD=""

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	install -d /usr/share/postgresql-common/pgdg && \
	curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc && \
	echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${DEBIAN_VERSION}-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
	apt-get update && \
	apt-get install -y postgresql-client-${PGVERSION}

FROM base-pg AS pg-basebackup

ENV BACKUP_CMD "/opt/parmincloud/backups/pg-basebackup"
COPY --chmod=0775 pg-basebackup.sh /opt/parmincloud/backups/pg-basebackup

FROM base-pg AS pg-dump

ENV BACKUP_CMD "/opt/parmincloud/backups/pg-dump"
COPY --chmod=0775 pg-dump.sh /opt/parmincloud/backups/pg-dump

FROM base AS mysql-dump

ENV BACKUP_CMD="/opt/parmincloud/backups/mysql-dump"

ENV MYSQL_HOST=""
ENV MYSQL_PORT=""
ENV MYSQL_USER=""
ENV MYSQL_PASSWORD=""
ENV DUMP_MODE="mysql"

RUN curl -L --output mysql-apt-confg.deb https://dev.mysql.com/get/mysql-apt-config_0.8.39-1_all.deb && \
	apt-get update && \
	apt-get install -y lsb-release wget && \
	dpkg -i ./mysql-apt-confg.deb && \
	rm -f mysql-apt-confg.deb

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y mysql-client

COPY --chmod=0775 mysql-dump.sh /opt/parmincloud/backups/mysql-dump

FROM base AS mariadb-dump
ENV BACKUP_CMD="/opt/parmincloud/backups/mysql-dump"

ENV MARIADB_HOST=""
ENV MARIADB_PORT=""
ENV MARIADB_USER=""
ENV MARIADB_PASSWORD=""
ENV DUMP_MODE="mariadb"

RUN curl -L --output mariadb_repo_setup https://downloads.mariadb.com/MariaDB/mariadb_repo_setup && \
	apt-get update && \
	apt-get install -y lsb-release wget && \
	chmod a+x ./mariadb_repo_setup && \
	./mariadb_repo_setup --mariadb-server-version="mariadb-12.2.2" \
	rm -f mariadb_repo_setup

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y mariadb-client

COPY --chmod=0775 mysql-dump.sh /opt/parmincloud/backups/mysql-dump



FROM base AS ssh-file

ENV BACKUP_CMD="/opt/parmincloud/backups/ssh-file"
ENV DATA_DIR="/data"

ENV SSH_HOST=""
ENV SSH_PORT="22"
ENV SSH_USER=""
ENV SSH_PASSWORD=""
ENV SSH_PRIVATE_KEY=""

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y openssh-client sshpass

COPY --chmod=0775 ssh-file.sh /opt/parmincloud/backups/ssh-file

FROM base AS ssh-command

ENV BACKUP_CMD="/opt/parmincloud/backups/ssh-command"

ENV SSH_HOST=""
ENV SSH_PORT="22"
ENV SSH_USER=""
ENV SSH_PASSWORD=""
ENV SSH_PRIVATE_KEY=""
ENV SSH_COMMAND=""

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
	--mount=type=cache,target=/var/lib/apt,sharing=locked \
	apt-get update && \
	apt-get install -y openssh-client sshpass

COPY --chmod=0775 ssh-command.sh /opt/parmincloud/backups/ssh-command

FROM base AS mongo-dump

ENV BACKUP_CMD="/opt/parmincloud/backups/mongo-dump"

ENV MONGODB_URI=""

RUN curl -L https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian12-x86_64-100.16.1.deb -o mongodb-database-tools.deb && \
	dpkg -i mongodb-database-tools.deb && \
	rm mongodb-database-tools.deb -f

COPY --chmod=0775 mongo-dump.sh /opt/parmincloud/backups/mongo-dump
