on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/php.yaml
      - php/*
      - '!php/README.md'

permissions:
    contents: write
    packages: write

jobs:
  build-image:
    strategy:
      matrix:
        php_version:
          - version: "8.1"
            debian_version: bookworm
          - version: "8.2"
            debian_version: bookworm
          - version: "8.3"
            debian_version: bookworm
          - version: "8.4"
            debian_version: bookworm
          - version: "7.4"
            debian_version: bullseye
        runtime:
          - php: apache
            start: apache
          - php: cli
            start: cli
          - php: fpm
            start: fpm
          - php: fpm
            start: nginx

    name: Build Image
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: parmincloud/containers/php

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: build-and-push-release
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ./php
        file: ./php/Containerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        platforms: linux/amd64
        build-args: |
          PHP_RUNTIME=${{ matrix.runtime.php }}
          DEBIAN_VERSION=${{ matrix.php.debian_version }}
          PHP_VERSION=${{ matrix.php.version }}
          START_RUNTIME=${{ matrix.runtime.start }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:php${{ matrix.php_version }}-${{ matrix.runtime.start }}

